"""add lecs_hosts

Revision ID: a1b2c3d4e5f6
Revises: 37be9cca2b34
Create Date: 2026-05-09 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '37be9cca2b34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecs_hosts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=False),
    sa.Column('billing_mode', sa.String(length=16), nullable=False),
    sa.Column('instance_type', sa.String(length=32), nullable=False),
    sa.Column('spec_id', sa.String(length=32), nullable=False),
    sa.Column('vcpu', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('system_disk_gb', sa.Integer(), nullable=False),
    sa.Column('os_image', sa.String(length=32), nullable=False),
    sa.Column('ip_mode', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('ip_mask', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('creating', 'normal', 'failed', 'shutting_down', 'stopped', 'starting', 'deleting', 'deleted', name='hoststatus'), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('cost_info', sa.JSON(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lecs_hosts_user_id', 'lecs_hosts', ['user_id'], unique=False)
    op.create_index('ix_lecs_hosts_deleted_at', 'lecs_hosts', ['deleted_at'], unique=False)
    op.create_index('ix_lecs_hosts_user_id_deleted_at', 'lecs_hosts', ['user_id', 'deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lecs_hosts_user_id_deleted_at', table_name='lecs_hosts')
    op.drop_index('ix_lecs_hosts_deleted_at', table_name='lecs_hosts')
    op.drop_index('ix_lecs_hosts_user_id', table_name='lecs_hosts')
    op.drop_table('lecs_hosts')
    # ### end Alembic commands ###
